# L1 -- Happy-path import (tiny spec)
#
# 100K steps, workload, no mutations, no Safrole.

jam_spec = "tiny"
profile = "full"
fuzzy_profile = "full"
safrole = false
max_steps = 100000
max_work_items = 5
max_mutations = 0
# Use u32::max to enable target pause/resume
remote_timeout = 4294967295

# Shared
source = "local"
# Overwrite via `--target-sock` CLI option if required
target_sock = "/tmp/jam_fuzz/fuzz.sock"
step_period = 0
verbosity = 2
trace_dir = "traces"
skip_slots = false
single_step = false
show_config = false
pause_on_error = false
trace_traces = false
pvm_interpreter_backend = true
